/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.msi.userview;

import com.msi.DAO.ProductDAO;
import com.msi.adminview.Category;
import com.msi.adminview.Product;
import javax.swing.JTable;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author MSI
 */
public class BookmarkForm extends javax.swing.JFrame {

    /**
     * Creates new form BookmarkForm
     */
    public BookmarkForm() {
        initComponents();
        super.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PCat = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookmark = new javax.swing.JTable();
        btnUBM = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PCat2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUnBookmark = new javax.swing.JTable();
        btnBM = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PCatMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(PCat);

        tblBookmark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBookmark);

        btnUBM.setText("Unbookmark");
        btnUBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUBMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUBM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnUBM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bookmarked product", jPanel3);

        PCat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PCat2MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(PCat2);

        tblUnBookmark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblUnBookmark);

        btnBM.setText("Bookmark");
        btnBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnBM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Unbookmarked product", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PCatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCatMouseReleased
//         int row = tblBookmark.getSelectedRow();
//        String Table_click = (tblBookmark.getModel().getValueAt(row, 0).toString());
        ConfigurableApplicationContext context = new ClassPathXmlApplicationContext("com/msi/xml/AdminSpring.xml");
            ProductDAO proDAO = (ProductDAO) context.getBean("ProductDAO");
            Product product = new Product();
              Category cat=new Category();
            // product.setPName(Table_click);
             String Catname=(String) PCat.getSelectedValue();
       cat.setCatName(Catname);
      // System.out.print(cat.getCatName());
         proDAO.fillBookmarkedTable(cat,tblBookmark, lblEName.getText());
        context.close();
        
//        BookmarkAndUnBookmarkProductInfo baUBP = new BookmarkAndUnBookmarkProductInfo();
//        baUBP.fillBookmarkedTable((String) PCat.getSelectedValue(), tblBookmark, lblEName.getText());
    }//GEN-LAST:event_PCatMouseReleased

    private void btnUBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUBMActionPerformed
try{        
        int row = tblBookmark.getSelectedRow();
        String Table_click = (tblBookmark.getModel().getValueAt(row, 0).toString());
        ConfigurableApplicationContext context = new ClassPathXmlApplicationContext("com/msi/xml/AdminSpring.xml");
            ProductDAO proDAO = (ProductDAO) context.getBean("ProductDAO");
            Product product = new Product();
              Category cat=new Category();
             product.setPName(Table_click);
       cat.setCatName((String) PCat.getSelectedValue());
        proDAO.UnBookmarkedProduct(product, lblEName.getText());
        proDAO.fillBookmarkedTable(cat,tblBookmark, lblEName.getText());
        proDAO.fillUnBookmarkedTable(cat, tblUnBookmark, Table_click);
        context.close();
}catch(Exception e){
    
}
//        BookmarkAndUnBookmarkProductInfo baUBP = new BookmarkAndUnBookmarkProductInfo();
//        baUBP.fillBookmarkedTable((String) PCat.getSelectedValue(), tblBookmark, lblEName.getText());
    }//GEN-LAST:event_btnUBMActionPerformed

    private void PCat2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCat2MouseReleased
//      int row = tblBookmark.getSelectedRow();
//        String Table_click = (tblBookmark.getModel().getValueAt(row, 0).toString());
        ConfigurableApplicationContext context = new ClassPathXmlApplicationContext("com/msi/xml/AdminSpring.xml");
            ProductDAO proDAO = (ProductDAO) context.getBean("ProductDAO");
            Product product = new Product();
              Category cat=new Category();
             //product.setPName(Table_click);
       cat.setCatName((String) PCat2.getSelectedValue());
       
         proDAO.fillUnBookmarkedTable(cat,tblUnBookmark, lblEName.getText());
        context.close();


//     BookmarkAndUnBookmarkProductInfo baUBP = new BookmarkAndUnBookmarkProductInfo();
//       
//        baUBP.fillUnBookmarkedTable((String) PCat2.getSelectedValue(), tblUnBookmark, lblEName.getText());
    }//GEN-LAST:event_PCat2MouseReleased

    private void btnBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMActionPerformed
            //BookmarkAndUnBookmarkProductInfo baUBP = new BookmarkAndUnBookmarkProductInfo();
            try{
             int row = tblUnBookmark.getSelectedRow(); 
            String Table_click = (tblUnBookmark.getModel().getValueAt(row, 0).toString());
            ConfigurableApplicationContext context = new ClassPathXmlApplicationContext("com/msi/xml/AdminSpring.xml");
            ProductDAO proDAO = (ProductDAO) context.getBean("ProductDAO");
            Product product = new Product();
            Category cat=new Category();
            product.setPName(Table_click);
            cat.setCatName((String) PCat2.getSelectedValue());
            proDAO.bookmarkProduct(product, lblEName.getText().trim());
            proDAO.fillUnBookmarkedTable(cat, tblUnBookmark,lblEName.getText());
            proDAO.fillBookmarkedTable(cat,tblBookmark, lblEName.getText());
            context.close();
            }catch(Exception e){
               
            }
            
           // baUBP.bookmarkProduct(lblEName.getText().trim(),Table_click);
          //  baUBP.fillUnBookmarkedTable((String) PCat2.getSelectedValue(), tblUnBookmark, lblEName.getText());
           //System.out.print(Table_click);
            
    }//GEN-LAST:event_btnBMActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList PCat;
    public javax.swing.JList PCat2;
    public javax.swing.JButton btnBM;
    public javax.swing.JButton btnUBM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lblEName;
    public javax.swing.JTable tblBookmark;
    public javax.swing.JTable tblUnBookmark;
    // End of variables declaration//GEN-END:variables
}
